name: Validate Servers

on:
  pull_request:
    branches:
      - main

jobs:
  validate-servers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt
      - name: Run create_index.py
        run: |
          python scripts/create_index.py
